### ISSUE TITLE
How can see 3D map with building on mapkit swift 4?

### ISSUE THREAD

**Issue by ghost** [maximbilan/iOS-MapKit-Tutorial#1]
I have implemented mapkit 3D map building with swift 4.

but, it don't works now.

Do you have any solution?

Best regards

Anrei

**Comment by maximbilan** [comment]
Hi @AndreiOpanasenko,

Thanks for using my tutorial.
Please explain, what exactly doesn't work?

<img width="875" alt="screen shot 2018-01-12 at 19 36 59" src="https://user-images.githubusercontent.com/3020089/34887737-305b1378-f7d0-11e7-8455-7d6f7e360974.png">

**Comment by ghost** [comment]
Hello, Maximbilan
I want to implement like this map
![2016-05-06_06-32-43](https://user-images.githubusercontent.com/34819775/34888152-ea6f60f0-f77d-11e7-8146-089e56490717.png)

**Comment by ghost** [comment]
Hello, Maximbilan

Do you have any solution?

I think you can solve this problem.

**Comment by maximbilan** [comment]
This tutorial is about base using of MapKit for beginners. It's not about the flyover. You can find a lot of solutions on StackOverflow or somewhere else.
